apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: telefonica-action-template
  title: Custom new action
  description: Create a new custom action
  tags:
    - custom
spec:
  owner: victor.barrancofernandez@telefonica.com
  type: service
  parameters:
   - title: Choose url location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Swagger Location
          type: string
          ui:field: RepoUrlPicker

  steps:
    - id: codegen:create
      name: Create App in codegen
      action: codegen:create
