apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: telefonica-action-template
  title: Custom new action
  description: Create a new custom action
  tags:
    - custom
spec:
  owner: victor.barrancofernandez@telefonica.com
  type: service
  parameters:
    - title: Choose sawgger location
      required:
        - swaggerUrl
        - component_id
        - description
        - owner
      properties:
        swaggerUrl:
          title: Swagger
          type: string
          description: Location of the swagger
        component_id:
            title: Name
            type: string
            description: Unique name of the component
            ui:field: EntityNamePicker
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
  steps:
    - id: codegen:create
      name: Create App in codegen
      action: codegen:create
      input:
        values:
          repoUrl: ${{ parameters.swaggerUrl }}
